Add in a server exec command for running ad-hoc commands directly on the server
basecamp/kamal pull request #646
Opened 2024-01-12 06:03 UTC by nickhammond

2024-02-16 08:33 UTC, igor-alexandrov approved these changes

2024-03-04 11:51 UTC, djmb commented
Looks great @nickhammond 🙏

It think we should go ahead with the interactive version as well though - would you be able to add that?

2024-03-04 17:08 UTC, nickhammond commented
@djmb Yah, I'll explore that this week when I get some time.

2024-03-05 01:36 UTC, abuaboud commented
can't wait for this to be released. It's a small thing, but very crucial for us.

Thank you @nickhammond

2024-03-05 02:17 UTC, Sija commented
@djmb Perhaps the interactive version could be merged as a followup in order to proceed with this PR?

2024-05-13 12:39 UTC, abuaboud commented
Hi @nickhammond and @djmb,

Is there anything remaining in this PR or blocking? we would love to use it as soon as possible.

Thank you so much!

2024-05-13 20:59 UTC, nickhammond commented
@djmb Just added in the interactive version with `run_locally`. I'm not super familiar with SSHKit so if there's a better way to do this let me know. It mirrors the same options and flow that you'd normally use with an accessory or an app container to run exec.

2024-05-14 13:05 UTC, igor-alexandrov approved these changes
Great job! Thank you.

2024-05-20 08:21 UTC, djmb requested changes
Thanks @nickhammond - just a couple of minor suggestions, then I think we'll be good to go 👍

2024-05-20 08:21 UTC, djmb commented on lib/kamal/cli/server.rb
> +  desc "exec", "Run a custom command on the server(use --help to show options)"
```suggestion
  desc "exec", "Run a custom command on the server (use --help to show options)"
```

2024-05-20 08:21 UTC, djmb commented on lib/kamal/cli/server.rb
> +      host = hosts.first
```suggestion
      host = KAMAL.primary_host
```

2024-05-20 18:14 UTC, nickhammond reviewed
@djmb Thanks for the review and good call on the `primary_host` instead of first.

2024-05-20 22:39 UTC, Sija commented on lib/kamal/cli/server.rb
> +  option :interactive, type: :boolean, aliases: "-i", default: false, desc: "Run the command interactively(use for console/bash)"
```suggestion
  option :interactive, type: :boolean, aliases: "-i", default: false, desc: "Run the command interactively (use for console/bash)"
```

2024-05-21 10:33 UTC, djmb approved these changes

2024-05-21 10:34 UTC, djmb commented
Thanks @nickhammond!

2024-05-21 10:34 UTC, merged